### ISSUE TITLE
Ideas for better request matching

### ISSUE THREAD

**Issue by lnquy** [golovers/remedios#1]
1. We can put all mock handlers to a `map[string]handler` and later on just have to lookup on that map for the corresponding response.
The key of the map can be the combination of request method and request path. E.g.: GET:/api/v1/something.

2. For matching the body of request, if we force the user to define the 100% matched JSON body, then we can just convert body data to JSON compacted/minified format (no indentation, space...) then hash that data and later compare with the hash of mock response's body.

**Comment by pthethanh** [comment]
fixed :)
